name: Mirror official pilight repository
on:
  workflow_dispatch:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron: '1 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check for recent changes
      id: check_for_changes
      run: |
        commitdate=$(curl -sL "https://api.github.com/repos/pilight/pilight/commits/master" | jq -r ".commit.author.date")
        commitdays=$(( ( $(date --utc +%s) - $(date --utc -d $commitdate +%s) ) / 86400 ))
        echo "Last commit was $commitdays days ago."
        if [ $commitdays -lt 2 ]; then
          echo "::set-output name=changes_exist::true"
          echo "Schedule following steps to RUN."
        else
          echo "::set-output name=changes_exist::false"
          echo "Schedule following steps to NOT RUN."
        fi

    - name: Mirror
      if: ${{ steps.check_for_changes.outputs.changes_exist == 'true' }}
      run: |
        git clone --mirror 'https://github.com/pilight/pilight' mux.git
        cd mux.git
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git push github master staging rewrite --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
